initial= open("output.txt", "w")
write_data=initial.write(str(input("Enter the text to write to the file:\n")))
print("Data successfully written to output.txt")
initial.close()
initial=open("output.txt","a")
append_data=initial.write("\n"+str(input("Enter additional text to append:\n")))
print("Final content of output.txt:")
initial.close()
initial=open("output.txt","r")
read_data=initial.read()
print(read_data)
initial.close()